package _internal.github_dot_com.dlclark.regexp2.syntax;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.errors.Errors;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.strings.Strings;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.os.Os;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.sort.Sort;
@:keep @:follow @:using(_internal.github_dot_com.dlclark.regexp2.syntax.Syntax_t_nodetype_static_extension.T_nodeType_static_extension) typedef T_nodeTypePointer = stdgo.Pointer<_internal.github_dot_com.dlclark.regexp2.syntax.Syntax_t_nodetype.T_nodeType>;
