package _internal.github_dot_com.dlclark.regexp2.syntax;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.errors.Errors;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.strings.Strings;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.os.Os;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.sort.Sort;
@:named @:using(_internal.github_dot_com.dlclark.regexp2.syntax.Syntax_t_singlerangesorter_static_extension.T_singleRangeSorter_static_extension) typedef T_singleRangeSorter = stdgo.Slice<_internal.github_dot_com.dlclark.regexp2.syntax.Syntax_t_singlerange.T_singleRange>;
