package _internal.github_dot_com.dlclark.regexp2;
import stdgo._internal.regexp.Regexp;
import stdgo._internal.time.Time;
import stdgo._internal.fmt.Fmt;
import _internal.github_dot_com.dlclark.regexp2.syntax.Syntax;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.os.Os;
import stdgo._internal.log.Log;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.strings.Strings;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.encoding.json.Json;
import stdgo._internal.errors.Errors;
import stdgo._internal.sync.atomic_.Atomic_;
import stdgo._internal.unicode.Unicode;
@:keep @:follow @:using(_internal.github_dot_com.dlclark.regexp2.Regexp2_t__struct_0pointer_static_extension.T__struct_0Pointer_static_extension) typedef T__struct_0PointerPointer = stdgo.Pointer<_internal.github_dot_com.dlclark.regexp2.Regexp2_t__struct_0pointer.T__struct_0Pointer>;
